<a href="https://colab.research.google.com/github/Omkar210/Statistics-and-ML/blob/main/Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a1 = np.array([3,7,6,1,8,9])
a2 = np.array([2,4,5,8,10,3,6])

print(np.intersect1d(a1,a2))
print(np.union1d(a1,a2))

print(np.in1d(a1,a2)) # DeprecationWarning: instead use below command
print(np.isin(a1,a2))

[3 6 8]
[ 1  2  3  4  5  6  7  8  9 10]
[ True False  True False  True False]
[ True False  True False  True False]

/tmp/ipykernel_5458/652233031.py:7: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(a1,a2))

In [ ]:
print(np.setdiff1d(a1,a2))
print(np.setdiff1d(a2,a1))

[1 7 9]
[ 2  4  5 10]

In [ ]:
# either only in a1 or in a2
print(np.setxor1d(a1,a2))
print(np.where(np.isin(a1,a2))) # this is intersection of a1 and a2

[ 1  2  4  5  7  9 10]
(array([0, 2, 4]),)

Matrix multiplication:

Critiria -> No. of rows of A = No. of cols of B

Dot Product: There result will always be scaler, it might be negative and 0.

If result is 0 then it means vectors are perpendicular(orthogonal)

Then you have to find the dot product with |v1||v2|cos0

In [ ]:
x1 = np.array([2,3,-4])
x2 = np.array([3,-2,1])

print(np.dot(x1,x2))

-4

In [ ]:
# Linear algebra
from numpy import linalg

x3 = np.array([[1,2,3],[0,1,2],[1,1,0]])
print(np.linalg.det(x3)) # determinant value

# cross product
print(np.cross(x1,x2))

-1.0

array([ -5, -14, -13])

In [ ]:
from numpy import random

print(np.random.rand(10))
print(np.random.randint(5,50))
print(np.random.randint(5,50,15))

[0.12731651 0.66306129 0.87223825 0.67135802 0.23513449 0.96649232
 0.31349855 0.97783146 0.88944405 0.91558444]
44
[41 15 20 46 36 28 29 30 36 10  5 41 43 33 42]

# Pandas

In [ ]:
import pandas as pd

In [ ]:
x1 = [4,8,4,3,2]
s1 = pd.Series(x1)
s1 = pd.Series(x1,index=['A','B','C','D','E'])
s1

A    4
B    8
C    4
D    3
E    2
dtype: int64

In [ ]:
print(s1.iloc[2]) # index based extraction
print(s1.loc['D']) # label based extraction
print(s1.loc[['A','B']])
print(s1.iloc[[2,3]])

4
3
A    4
B    8
dtype: int64
C    4
D    3
dtype: int64

In [ ]:
s2 = pd.Series([1,2,3,4,5], index=['A','A','B','A','B'])
print(s2.iloc[3])
print(s2.loc['A'])

4
A    1
A    2
A    4
dtype: int64

In [ ]:
s3 = pd.Series([3,9], index=['F','G'])
s4 = pd.concat([s1,s3])
print(len(s4))
s4

7

A    4
B    8
C    4
D    3
E    2
F    3
G    9
dtype: int64

In [ ]:
s4.iloc[4] = 7
print(s4)

s4.loc['E'] = 11
print(s4)

A    4
B    8
C    4
D    3
E    7
F    3
G    9
4    7
dtype: int64
A     4
B     8
C     4
D     3
E    11
F     3
G     9
4     7
dtype: int64

In [ ]:
s5 = pd.concat([s2,s3])

s5.iloc[2] = 8
print(s5)

s5.loc['A'] = 13
print(s5)

A    1
A    2
B    8
A    4
B    5
F    3
G    9
dtype: int64
A    13
A    13
B     8
A    13
B     5
F     3
G     9
dtype: int64

In [ ]:
print(s4.drop(['D']))
# s5 = s5.drop(['G'])
print(s4)
print(s5)

s5.drop(s5.index[[2,4]])

A     4
B     8
C     4
E    11
F     3
G     9
4     7
dtype: int64
A     4
B     8
C     4
D     3
E    11
F     3
G     9
4     7
dtype: int64
A    13
A    13
B     8
A    13
B     5
F     3
dtype: int64

A    13
A    13
A    13
F     3
dtype: int64

In [ ]:
s4 = pd.Series([1,2,4,5,9,4,2,5,7,3,5,5,4,6,7,7,8])
s5 = s4.value_counts()
print(s5)

5    4
7    3
4    3
2    2
1    1
9    1
3    1
6    1
8    1
Name: count, dtype: int64

In [ ]:
print(s5.iloc[2])
print(s5.loc[5])

# What if we only have values then how to find
np.where(s5==3)
s5.index[np.where(s5==3)]

3
4

Index([7, 4], dtype='int64')

# DataFrame

In [ ]:
mydata = [
    ['A',1234,80000],
    ['B',4567,10000],
    ['C',6789,12888],
    ['D',5678,13000]
]

In [ ]:
# indices are getting carry forward in this dataframe
mydf = pd.DataFrame(mydata)
mydf = pd.DataFrame(mydata, columns=['Name','AccNo','Balance'])
temp = pd.DataFrame(mydata, columns=['Name','AccNo','Balance'],index=['Omkar','Chaitu','Sujal','Chikki'])

print(mydf)
print(temp)

  Name  AccNo  Balance
0    A   1234    80000
1    B   4567    10000
2    C   6789    12888
3    D   5678    13000
       Name  AccNo  Balance
Omkar     A   1234    80000
Chaitu    B   4567    10000
Sujal     C   6789    12888
Chikki    D   5678    13000

In [ ]:
df = mydf.loc[[1,2]]
print(df)
print(df.iloc[1])
print(df.loc[1])

  Name  AccNo  Balance
1    B   4567    10000
2    C   6789    12888
Name           C
AccNo       6789
Balance    12888
Name: 2, dtype: object
Name           B
AccNo       4567
Balance    10000
Name: 1, dtype: object

In [ ]:
# label from the original dataframe will get reset index
df = mydf.loc[[1,2]].reset_index(drop=True) # this will reset index

df = mydf.loc[[1,2]].reset_index(drop=False) # this will reset index but create new column of previous label

print(df)

   index Name  AccNo  Balance
0      1    B   4567    10000
1      2    C   6789    12888

Dictionary DataFrame

In [ ]:
stu_info = {
    'Name': ['Omkar','Chaitu','Sujal','Chikki','Debu'],
    'RollNo': [1,2,3,4,5],
    'Marks': [50,60,75,64,77]
}

In [ ]:
# if data has already column name and we try to change the column name then it will create new dataframe with empty index and values
df = pd.DataFrame(stu_info, columns=['naav','number','marks'])
print(df)

Empty DataFrame
Columns: [naav, number, marks]
Index: []

In [ ]:
df = pd.DataFrame(stu_info)
print(df)

     Name  RollNo  Marks
0   Omkar       1     50
1  Chaitu       2     60
2   Sujal       3     75
3  Chikki       4     64
4    Debu       5     77

In [ ]:
# don't do this things
newdf = pd.DataFrame([['E',7,80],['F',8,30]])
pd.concat([df,newdf])

     Name  RollNo  Marks    0    1     2
0   Omkar     1.0   50.0  NaN  NaN   NaN
1  Chaitu     2.0   60.0  NaN  NaN   NaN
2   Sujal     3.0   75.0  NaN  NaN   NaN
3  Chikki     4.0   64.0  NaN  NaN   NaN
4    Debu     5.0   77.0  NaN  NaN   NaN
0     NaN     NaN    NaN    E  7.0  80.0
1     NaN     NaN    NaN    F  8.0  30.0

In [ ]:
newdf = pd.DataFrame([['E',7,80],['F',8,30]], columns=df.columns)
print(pd.concat([df,newdf]))
print()
newdf = pd.DataFrame([['E',7,80],['F',8,30]], columns=df.columns)
df1 = pd.concat([df,newdf]).reset_index(drop=True)
df1

     Name  RollNo  Marks
0   Omkar       1     50
1  Chaitu       2     60
2   Sujal       3     75
3  Chikki       4     64
4    Debu       5     77
0       E       7     80
1       F       8     30

     Name  RollNo  Marks
0   Omkar       1     50
1  Chaitu       2     60
2   Sujal       3     75
3  Chikki       4     64
4    Debu       5     77
5       E       7     80
6       F       8     30

In [ ]:
x1 = [67,89,75,62,59,82,73]
# df2 = df1.copy() # if we change the column name which is already present in df then it will change that column's values
df1['Marks2'] = x1
df1

     Name  RollNo  Marks  Marks2
0   Omkar       1     50      67
1  Chaitu       2     60      89
2   Sujal       3     75      75
3  Chikki       4     64      62
4    Debu       5     77      59
5       E       7     80      82
6       F       8     30      73

In [ ]:
df1.at[3,'Marks'] # similar to loc: might not work for large dataset
df1.iat[1,3] # similar to iloc: might not work for large dataset

np.int64(89)

In [ ]:
df1.iloc[[0,3,5]].reset_index(drop=True)

     Name  RollNo  Marks  Marks2
0   Omkar       1     50      67
1  Chikki       4     64      62
2       E       7     80      82

In [ ]:
df1[['Name','Marks2']]  # with same way as above we can extract columns
df1.iloc[:,[0,3]]

np.int64(50)

In [ ]:
# Single Column Extraction
df1['Marks2']
df1.Marks2
# same methods to extract column from df

0    67
1    89
2    75
3    62
4    59
5    82
6    73
Name: Marks2, dtype: int64

In [ ]:
# Drop Columns
df1.drop([1,4],axis=0).reset_index(drop=True)
df1.drop(['RollNo','Marks2'],axis=1)

     Name  Marks
0   Omkar     50
1  Chaitu     60
2   Sujal     75
3  Chikki     64
4    Debu     77
5       E     80
6       F     30

In [ ]:
import os
os.chdir('/content/drive/MyDrive/CDAC')

In [ ]:
os.getcwd()

'/content/drive/MyDrive/CDAC'

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='ERPData')
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
# Using the df1 DataFrame, first, select only the rows where 'Marks' are greater than 70 AND 'Marks2' are less than 80. Then, from this filtered DataFrame, drop the 'RollNo' column. Finally, display the resulting DataFrame.

print(df1)
NewDf = df1[(df1['Marks']>70) & (df1['Marks2']<80)].drop('RollNo',axis=1)
NewDf

     Name  RollNo  Marks  Marks2
0   Omkar       1     50      67
1  Chaitu       2     60      89
2   Sujal       3     75      75
3  Chikki       4     64      62
4    Debu       5     77      59
5       E       7     80      82
6       F       8     30      73

    Name  Marks  Marks2
2  Sujal     75      75
4   Debu     77      59