<a href="https://colab.research.google.com/github/Omkar210/Statistics-and-ML/blob/main/Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [9]:
a1 = np.array([3,7,6,1,8,9])
a2 = np.array([2,4,5,8,10,3,6])

print(np.intersect1d(a1,a2))
print(np.union1d(a1,a2))

print(np.in1d(a1,a2)) # DeprecationWarning: instead use below command
print(np.isin(a1,a2))

[3 6 8]
[ 1  2  3  4  5  6  7  8  9 10]
[ True False  True False  True False]
[ True False  True False  True False]

/tmp/ipykernel_5458/652233031.py:7: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(a1,a2))

In [6]:
print(np.setdiff1d(a1,a2))
print(np.setdiff1d(a2,a1))

[1 7 9]
[ 2  4  5 10]

In [11]:
# either only in a1 or in a2
print(np.setxor1d(a1,a2))
print(np.where(np.isin(a1,a2))) # this is intersection of a1 and a2

[ 1  2  4  5  7  9 10]
(array([0, 2, 4]),)

Matrix multiplication:

Critiria -> No. of rows of A = No. of cols of B

Dot Product: There result will always be scaler, it might be negative and 0.

If result is 0 then it means vectors are perpendicular(orthogonal)

Then you have to find the dot product with |v1||v2|cos0

In [12]:
x1 = np.array([2,3,-4])
x2 = np.array([3,-2,1])

print(np.dot(x1,x2))

-4

In [15]:
# Linear algebra
from numpy import linalg

x3 = np.array([[1,2,3],[0,1,2],[1,1,0]])
print(np.linalg.det(x3)) # determinant value

# cross product
print(np.cross(x1,x2))

-1.0

array([ -5, -14, -13])

In [18]:
from numpy import random

print(np.random.rand(10))
print(np.random.randint(5,50))
print(np.random.randint(5,50,15))

array([15, 19, 44, 41, 27, 40, 31, 44,  6,  7, 48, 32, 24, 49, 33])

# Pandas

In [19]:
import pandas as pd

In [22]:
x1 = [4,8,4,3,2]
s1 = pd.Series(x1)
s1 = pd.Series(x1,index=['A','B','C','D','E'])
s1

A    4
B    8
C    4
D    3
E    2
dtype: int64

In [28]:
print(s1.iloc[2]) # index based extraction
print(s1.loc['D']) # label based extraction
print(s1.loc[['A','B']])
print(s1.iloc[[2,3]])

4
3
A    4
B    8
dtype: int64
C    4
D    3
dtype: int64

In [30]:
s2 = pd.Series([1,2,3,4,5], index=['A','A','B','A','B'])
print(s2.iloc[3])
print(s2.loc['A'])

4
A    1
A    2
A    4
dtype: int64

In [38]:
s3 = pd.Series([3,9], index=['F','G'])
s4 = pd.concat([s1,s3])
print(len(s4))
s4

7

A    4
B    8
C    4
D    3
E    2
F    3
G    9
dtype: int64

In [40]:
s4.iloc[4] = 7
print(s4)

s4.loc['E'] = 11
print(s4)

A    4
B    8
C    4
D    3
E    7
F    3
G    9
4    7
dtype: int64
A     4
B     8
C     4
D     3
E    11
F     3
G     9
4     7
dtype: int64

In [42]:
s5 = pd.concat([s2,s3])

s5.iloc[2] = 8
print(s5)

s5.loc['A'] = 13
print(s5)

A    1
A    2
B    8
A    4
B    5
F    3
G    9
dtype: int64
A    13
A    13
B     8
A    13
B     5
F     3
G     9
dtype: int64

In [50]:
print(s4.drop(['D']))
# s5 = s5.drop(['G'])
print(s4)
print(s5)

s5.drop(s5.index[[2,4]])

A     4
B     8
C     4
E    11
F     3
G     9
4     7
dtype: int64
A     4
B     8
C     4
D     3
E    11
F     3
G     9
4     7
dtype: int64
A    13
A    13
B     8
A    13
B     5
F     3
dtype: int64

A    13
A    13
A    13
F     3
dtype: int64

In [51]:
s4 = pd.Series([1,2,4,5,9,4,2,5,7,3,5,5,4,6,7,7,8])
s5 = s4.value_counts()
print(s5)

5    4
7    3
4    3
2    2
1    1
9    1
3    1
6    1
8    1
Name: count, dtype: int64

In [62]:
print(s5.iloc[2])
print(s5.loc[5])

# What if we only have values then how to find
np.where(s5==3)
s5.index[np.where(s5==3)]

3
4

Index([7, 4], dtype='int64')

# DataFrame

In [63]:
mydata = [
    ['A',1234,80000],
    ['B',4567,10000],
    ['C',6789,12888],
    ['D',5678,13000]
]

In [65]:
# indices are getting carry forward in this dataframe
mydf = pd.DataFrame(mydata)
mydf = pd.DataFrame(mydata, columns=['Name','AccNo','Balance'])
temp = pd.DataFrame(mydata, columns=['Name','AccNo','Balance'],index=['Omkar','Chaitu','Sujal','Chikki'])

print(mydf)
print(temp)

  Name  AccNo  Balance
0    A   1234    80000
1    B   4567    10000
2    C   6789    12888
3    D   5678    13000
       Name  AccNo  Balance
Omkar     A   1234    80000
Chaitu    B   4567    10000
Sujal     C   6789    12888
Chikki    D   5678    13000

In [70]:
df = mydf.loc[[1,2]]
print(df)
print(df.iloc[1])
print(df.loc[1])

  Name  AccNo  Balance
1    B   4567    10000
2    C   6789    12888
Name           C
AccNo       6789
Balance    12888
Name: 2, dtype: object
Name           B
AccNo       4567
Balance    10000
Name: 1, dtype: object

In [72]:
# label from the original dataframe will get reset index
df = mydf.loc[[1,2]].reset_index(drop=True) # this will reset index

df = mydf.loc[[1,2]].reset_index(drop=False) # this will reset index but create new column of previous label

print(df)

   index Name  AccNo  Balance
0      1    B   4567    10000
1      2    C   6789    12888