<a href="https://colab.research.google.com/github/Omkar210/Statistics-and-ML/blob/main/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [112]:
import numpy as np
import pandas as pd

In [113]:
import os

In [114]:
os.getcwd()

'/content/drive/My Drive/CDAC'

In [ ]:
os.chdir('/content/drive/MyDrive/CDAC')

In [171]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='ERPData')
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
df.tail(3)

   MaterialID Location  Quantity
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [ ]:
df.shape   # dimentions

(50, 3)

Unique Material IDs

In [ ]:
# Unique material IDs
np.unique(df['MaterialID'])
len(np.unique(df['MaterialID']))   # number of unique Material ID

6

Unique Location

In [ ]:
np.unique(df['Location'])
len(np.unique(df['Location']))  # number of unique location

5

Column Name Change

In [ ]:
df.columns.values

array(['MaterialID', 'Location', 'Quantity'], dtype=object)

In [ ]:
df.columns.values[0]

'MaterialID'

In [ ]:
df.columns.values[0] = 'MatID'
df.head()

  MaterialID Location  Quantity
0      MatID    MWH-4        34
1      MatID    MWH-1        67
2      MatID    MWH-2        27
3      MatID    MWH-5        65
4      MatID    MWH-4        36

Where Quantity is greater than 70

In [ ]:
print(len(df.iloc[np.where(df.Quantity>70)]))
print(df.iloc[np.where(df.Quantity>70)])
print(df.iloc[np.where(df.Quantity>70)].count())
print((df.Quantity>70).sum())

ind = np.where(df.Quantity>70)[0]
df.iloc[ind]

14
   MaterialID Location  Quantity
5       MatID    MWH-4        78
9       MatID    MWH-1       120
12      MatID    MWH-4        76
15      MatID    MWH-2        87
17      MatID    MWH-5       102
21      MatID    MWH-4        75
23      MatID    MWH-5        71
24      MatID    MWH-1       152
25      MatID    MWH-1       109
27      MatID    MWH-5        83
33      MatID    MWH-5       112
39      MatID    MWH-1       145
46      MatID    MWH-2        85
48      MatID    MWH-1        75
MaterialID    14
Location      14
Quantity      14
dtype: int64
14

   MaterialID Location  Quantity
5       MatID    MWH-4        78
9       MatID    MWH-1       120
12      MatID    MWH-4        76
15      MatID    MWH-2        87
17      MatID    MWH-5       102
21      MatID    MWH-4        75
23      MatID    MWH-5        71
24      MatID    MWH-1       152
25      MatID    MWH-1       109
27      MatID    MWH-5        83
33      MatID    MWH-5       112
39      MatID    MWH-1       145
46      MatID    MWH-2        85
48      MatID    MWH-1        75

In [ ]:
ind = np.where((df.Quantity>=70) & (df.Location=='MWH-1'))
print(len(ind[0]))

df2 = df.iloc[ind]
print(df2)

5
   MaterialID Location  Quantity
9       MatID    MWH-1       120
24      MatID    MWH-1       152
25      MatID    MWH-1       109
39      MatID    MWH-1       145
48      MatID    MWH-1        75

In [ ]:
ind = np.where((df.Quantity>=70) | (df.Location=='MWH-1'))
print(len(ind[0]))

df3 = df.iloc[ind]
print(df3.head())

21
   MaterialID Location  Quantity
1       MatID    MWH-1        67
5       MatID    MWH-4        78
9       MatID    MWH-1       120
10      MatID    MWH-1        34
12      MatID    MWH-4        76

Weight of location MWH-2

In [ ]:
# Weight of location MWH-2
n2 = df.iloc[np.where(df.Location=='MWH-2')]
print(sum(n2.Quantity))

sum(df.iloc[np.where(df.Location=='MWH-2')].Quantity)

397

In [ ]:
(df.Quantity<50).sum()

np.int64(24)

In [ ]:
# drop the row where quantity is less than 50
# df.drop(df.Quantity[df.Quantity<50].index)
# df.shape

# ind = np.where(df.Quantity<50)[0]
df1 = df.drop(np.where(df.Quantity<50)[0])
print(df1.head())
df1.shape

   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
3     AXCP-78    MWH-5        65
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
11    SDRT-67    MWH-4        58

(26, 3)

In [ ]:
df2 = df.drop(np.where(df.Quantity<50)[0]).reset_index(drop=True)
print(df2.head())
df2.shape

  MaterialID Location  Quantity
0    AXCP-78    MWH-1        67
1    AXCP-78    MWH-5        65
2    TMI-43T    MWH-4        78
3    TMI-43T    MWH-1       120
4    SDRT-67    MWH-4        58

(26, 3)

Add new column in dataframe

In [116]:
grade = []

for i in df.Quantity:
    if i <= 50:
        grade.append('A')
    elif i < 100:
        grade.append('B')
    else:
        grade.append('C')

['A',
 'B',
 'A',
 'B',
 'A',
 'B',
 'A',
 'A',
 'A',
 'C',
 'A',
 'B',
 'B',
 'A',
 'B',
 'B',
 'A',
 'C',
 'A',
 'B',
 'A',
 'B',
 'A',
 'B',
 'C',
 'C',
 'B',
 'B',
 'A',
 'B',
 'A',
 'B',
 'A',
 'C',
 'A',
 'A',
 'A',
 'B',
 'B',
 'C',
 'A',
 'B',
 'A',
 'A',
 'A',
 'B',
 'B',
 'A',
 'B',
 'A']

In [120]:
df['Grade'] = grade
df

   MaterialID Location  Quantity Grade
0     TMI-43T    MWH-4        34     A
1     AXCP-78    MWH-1        67     B
2     LXCV-21    MWH-2        27     A
3     AXCP-78    MWH-5        65     B
4     AXCP-78    MWH-4        36     A
5     TMI-43T    MWH-4        78     B
6     TMI-43T    MWH-4        31     A
7     TMI-43T    MWH-2        29     A
8     GCVB-79    MWH-2        10     A
9     TMI-43T    MWH-1       120     C
10    SDRT-67    MWH-1        34     A
11    SDRT-67    MWH-4        58     B
12    TMI-43T    MWH-4        76     B
13    TMI-43T    MWH-4        32     A
14    TMI-43T    MWH-3        65     B
15    GCVB-79    MWH-2        87     B
16    SDRT-67    MWH-5        12     A
17    SDRT-67    MWH-5       102     C
18    TMI-43T    MWH-4        34     A
19    TMI-43T    MWH-4        52     B
20    TMI-43T    MWH-4        39     A
21    TMI-43T    MWH-4        75     B
22    DDBN-89    MWH-4        48     A
23    DDBN-89    MWH-5        71     B
24    AXCP-78    MWH-1       152     C
25    AXCP-78    MWH-1       109     C
26    DDBN-89    MWH-1        57     B
27    LXCV-21    MWH-5        83     B
28    LXCV-21    MWH-5        34     A
29    LXCV-21    MWH-5        57     B
30    DDBN-89    MWH-4        27     A
31    TMI-43T    MWH-4        65     B
32    TMI-43T    MWH-4        43     A
33    TMI-43T    MWH-5       112     C
34    GCVB-79    MWH-5        26     A
35    GCVB-79    MWH-2        31     A
36    GCVB-79    MWH-2        28     A
37    AXCP-78    MWH-5        65     B
38    AXCP-78    MWH-5        70     B
39    AXCP-78    MWH-1       145     C
40    DDBN-89    MWH-1        34     A
41    SDRT-67    MWH-1        57     B
42    SDRT-67    MWH-2        31     A
43    DDBN-89    MWH-3        38     A
44    LXCV-21    MWH-3        42     A
45    DDBN-89    MWH-2        69     B
46    AXCP-78    MWH-2        85     B
47    AXCP-78    MWH-3        29     A
48    AXCP-78    MWH-1        75     B
49    DDBN-89    MWH-1        39     A

Frequency of Grades

In [126]:
print((df.Grade=='A').sum(), (df.Grade=='B').sum(),(df.Grade=='C').sum())

print(df.Grade.value_counts())

24 20 6
Grade
A    24
B    20
C     6
Name: count, dtype: int64

In [215]:
df

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [222]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [232]:
# name of warehouse where total number of quantity of consignments is highest
# output: Location and total

ans = df.groupby('Location').sum().sort_values(by='Quantity',ascending=False)
print(ans.index[0] , ans.Quantity[0])

# print(df)

count = {}
for i in np.unique(df.Location):
    if i in count:
        count[i] += df.iloc[np.where(df.Location==i)].Quantity.sum()
    else:
        count[i] = df.iloc[np.where(df.Location==i)].Quantity.sum()

print(max(count,key=count.get), count[max(count,key=count.get)])

MWH-1 889
MWH-1 889

/tmp/ipykernel_1287/2798229096.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(ans.index[0] , ans.Quantity[0])

# 🔥 Data Cleaning

In [158]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='EmpInfo')
df.head()

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342      NaN  RF453432
4    Rishi  R475    Prodn  DF453278

Department Column have null Values or not

In [159]:
ind = np.where(df.Deptt.isnull())
ind

(array([3, 5]),)

Create two different dataframe where Department is missing or not respectively

In [160]:
df1 = df.iloc[np.where(df.Deptt.isnull())[0]].reset_index(drop=True)
df1

     Name EmpID Deptt  Passport
0   Arjun  A342   NaN  RF453432
1  Chetan   NaN   NaN  ER534867

In [161]:
df2 = df.drop(np.where(df.Deptt.isnull())[0]).reset_index(drop=True)
df2

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Rishi  R475    Prodn  DF453278
4   Deepak   NaN  Quality  RF453432

Deptt and EmpId is missing

In [162]:
df.iloc[np.where(df.Deptt.isnull() & df.EmpID.isnull())[0]].reset_index(drop=True)

     Name EmpID Deptt  Passport
0  Chetan   NaN   NaN  ER534867

Change where Deptt is null value to Fresher

In [166]:
df.iloc[np.where(df.Deptt.isnull())[0],2] = 'Fresher'
df

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
2      NaN  J436    Admin  DF453278
3    Arjun  A342  Fresher  RF453432
4    Rishi  R475    Prodn  DF453278
5   Chetan   NaN  Fresher  ER534867
6   Deepak   NaN  Quality  RF453432

Don't want any missing values in the dataset then use dropna()

In [167]:
temp = df.dropna()
temp

      Name EmpID    Deptt  Passport
0   Sudeep  A342  Quality  DF453278
1  Ruchika  C578    Sales  CA567657
3    Arjun  A342  Fresher  RF453432
4    Rishi  R475    Prodn  DF453278

Information of Dataset

In [168]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   EmpID     5 non-null      object
 2   Deptt     7 non-null      object
 3   Passport  7 non-null      object
dtypes: object(4)
memory usage: 356.0+ bytes

Check Duplicate Values

In [170]:
# keeping the duplicated values and showing only second occurance of duplicated value
ind = np.where(df.Passport.duplicated())[0]

# this will not keep the duplicated value
ind = np.where(df.Passport.duplicated(keep=False))[0]

array([0, 2, 3, 4, 6])

In [ ]:
ind = np.where((df.Quantity>60) & (df.Quantity<110))
print(len(ind[0]))

In [197]:
# Pan Card Validation
import random
letter = ['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z']
number = ['0','1','2','3','4','5','6','7','8','9']

pan_no = ''.join(random.choices(letter,k=5))
pan_no = pan_no + ''.join(random.choices(number,k=4))
pan_no = pan_no + ''.join(random.choices(letter,k=1))
pan_no

'QGCTP1963H'

GroupBy Command

In [253]:
grp1 = df.groupby('Location')

# Grouping has been done based on the location
print(grp1.groups)

# print perticular group
df1 = grp1.get_group('MWH-3').reset_index(drop=True)
print(df1)

# print multiple group at a time
print(pd.concat([grp1.get_group('MWH-2'),grp1.get_group('MWH-3')]))

# sum of all Quantity present in each group
# reset_index will get you label in column and index is independent
df2 = grp1.Quantity.agg('sum').reset_index()
print(df2)

# this will give you how many time that record is in dataframe
# counting the total number of records are present in each groups
print(grp1.Quantity.agg('size'))
print(grp1.Quantity.agg('mean'))
print(grp1.Quantity.agg('median'))

# multiple aggregate function is used in one function
print(grp1.Quantity.agg(['sum','mean','size']))

{'MWH-1': [1, 9, 10, 24, 25, 26, 39, 40, 41, 48, 49], 'MWH-2': [2, 7, 8, 15, 35, 36, 42, 45, 46], 'MWH-3': [14, 43, 44, 47], 'MWH-4': [0, 4, 5, 6, 11, 12, 13, 18, 19, 20, 21, 22, 30, 31, 32], 'MWH-5': [3, 16, 17, 23, 27, 28, 29, 33, 34, 37, 38]}
  MaterialID Location  Quantity
0    TMI-43T    MWH-3        65
1    DDBN-89    MWH-3        38
2    LXCV-21    MWH-3        42
3    AXCP-78    MWH-3        29
   MaterialID Location  Quantity
2     LXCV-21    MWH-2        27
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
15    GCVB-79    MWH-2        87
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
42    SDRT-67    MWH-2        31
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
14    TMI-43T    MWH-3        65
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
47    AXCP-78    MWH-3        29
  Location  Quantity
0    MWH-1       889
1    MWH-2       397
2    MWH-3       174
3    MWH-4       728
4    MWH-5       697
Location
MWH-1    11
MWH-2     9
MWH-3     4
MWH-4    15
MWH-5    11
Name: Quantity, dtype: int64
Location
MWH-1    80.818182
MWH-2    44.111111
MWH-3    43.500000
MWH-4    48.533333
MWH-5    63.363636
Name: Quantity, dtype: float64
Location
MWH-1    67.0
MWH-2    31.0
MWH-3    40.0
MWH-4    43.0
MWH-5    65.0
Name: Quantity, dtype: float64
          sum       mean  size
Location
MWH-1     889  80.818182    11
MWH-2     397  44.111111     9
MWH-3     174  43.500000     4
MWH-4     728  48.533333    15
MWH-5     697  63.363636    11

Multi-Index or Multi-level labels

In [256]:
locn1 = ['Mumbai','Mumbai','Mumbai','Pune','Pune']
course = ['AI','ML','DS','AI','DS']
marks1 = [45,78,65,35,89]
marks2 = [80,76,59,82,49]

mydf = pd.DataFrame({'Omkar':marks1,'Chaitu':marks2},index=[locn1,course])
mydf

           Omkar  Chaitu
Mumbai AI     45      80
       ML     78      76
       DS     65      59
Pune   AI     35      82
       DS     89      49

In [257]:
# index Name will be applied to labels
# this type label/index is called multi-index where index name is empty by default
mydf.index.names = ['Location','Subject']
mydf

                  Omkar  Chaitu
Location Subject
Mumbai   AI          45      80
         ML          78      76
         DS          65      59
Pune     AI          35      82
         DS          89      49

In [259]:
# print on basis of primary index
print(mydf.loc['Mumbai'])

# print only for AI Subject from Mumbai region using both level of index/label
mydf.loc[('Mumbai','AI')]

         Omkar  Chaitu
Subject
AI          45      80
ML          78      76
DS          65      59

Omkar     45
Chaitu    80
Name: (Mumbai, AI), dtype: int64

In [260]:
# only in case of secondary index, we have to use .xs method
mydf.xs('AI',level='Subject')

          Omkar  Chaitu
Location
Mumbai       45      80
Pune         35      82