<a href="https://colab.research.google.com/github/Omkar210/Statistics-and-ML/blob/main/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
import os

In [7]:
os.getcwd()

'/content/drive/MyDrive/CDAC'

In [6]:
os.chdir('/content/drive/MyDrive/CDAC')

In [99]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='ERPData')
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [9]:
df.tail(3)

   MaterialID Location  Quantity
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [11]:
df.shape   # dimentions

(50, 3)

Unique Material IDs

In [23]:
# Unique material IDs
np.unique(df['MaterialID'])
len(np.unique(df['MaterialID']))   # number of unique Material ID

6

Unique Location

In [26]:
np.unique(df['Location'])
len(np.unique(df['Location']))  # number of unique location

5

Column Name Change

In [28]:
df.columns.values

array(['MaterialID', 'Location', 'Quantity'], dtype=object)

In [29]:
df.columns.values[0]

'MaterialID'

In [34]:
df.columns.values[0] = 'MatID'
df.head()

  MaterialID Location  Quantity
0      MatID    MWH-4        34
1      MatID    MWH-1        67
2      MatID    MWH-2        27
3      MatID    MWH-5        65
4      MatID    MWH-4        36

Where Quantity is greater than 70

In [48]:
print(len(df.iloc[np.where(df.Quantity>70)]))
print(df.iloc[np.where(df.Quantity>70)])
print(df.iloc[np.where(df.Quantity>70)].count())
print((df.Quantity>70).sum())

ind = np.where(df.Quantity>70)[0]
df.iloc[ind]

14
   MaterialID Location  Quantity
5       MatID    MWH-4        78
9       MatID    MWH-1       120
12      MatID    MWH-4        76
15      MatID    MWH-2        87
17      MatID    MWH-5       102
21      MatID    MWH-4        75
23      MatID    MWH-5        71
24      MatID    MWH-1       152
25      MatID    MWH-1       109
27      MatID    MWH-5        83
33      MatID    MWH-5       112
39      MatID    MWH-1       145
46      MatID    MWH-2        85
48      MatID    MWH-1        75
MaterialID    14
Location      14
Quantity      14
dtype: int64
14

   MaterialID Location  Quantity
5       MatID    MWH-4        78
9       MatID    MWH-1       120
12      MatID    MWH-4        76
15      MatID    MWH-2        87
17      MatID    MWH-5       102
21      MatID    MWH-4        75
23      MatID    MWH-5        71
24      MatID    MWH-1       152
25      MatID    MWH-1       109
27      MatID    MWH-5        83
33      MatID    MWH-5       112
39      MatID    MWH-1       145
46      MatID    MWH-2        85
48      MatID    MWH-1        75

In [57]:
ind = np.where((df.Quantity>=70) & (df.Location=='MWH-1'))
print(len(ind[0]))

df2 = df.iloc[ind]
print(df2)

5
   MaterialID Location  Quantity
9       MatID    MWH-1       120
24      MatID    MWH-1       152
25      MatID    MWH-1       109
39      MatID    MWH-1       145
48      MatID    MWH-1        75

In [60]:
ind = np.where((df.Quantity>=70) | (df.Location=='MWH-1'))
print(len(ind[0]))

df3 = df.iloc[ind]
print(df3.head())

21
   MaterialID Location  Quantity
1       MatID    MWH-1        67
5       MatID    MWH-4        78
9       MatID    MWH-1       120
10      MatID    MWH-1        34
12      MatID    MWH-4        76

In [77]:
# Weight of location MWH-2
n2 = df.iloc[np.where(df.Location=='MWH-2')]
print(sum(n2.Quantity))

sum(df.iloc[np.where(df.Location=='MWH-2')].Quantity)

397

In [84]:
(df.Quantity<50).sum()

np.int64(24)

In [105]:
# drop the row where quantity is less than 50
# df.drop(df.Quantity[df.Quantity<50].index)
# df.shape

# ind = np.where(df.Quantity<50)[0]
df1 = df.drop(np.where(df.Quantity<50)[0])
print(df1.head())
df1.shape

   MaterialID Location  Quantity
1     AXCP-78    MWH-1        67
3     AXCP-78    MWH-5        65
5     TMI-43T    MWH-4        78
9     TMI-43T    MWH-1       120
11    SDRT-67    MWH-4        58

(26, 3)

In [111]:
df2 = df.drop(np.where(df.Quantity<50)[0]).reset_index(drop=True)
print(df2.head())
df2.shape

  MaterialID Location  Quantity
0    AXCP-78    MWH-1        67
1    AXCP-78    MWH-5        65
2    TMI-43T    MWH-4        78
3    TMI-43T    MWH-1       120
4    SDRT-67    MWH-4        58

(26, 3)