<a href="https://colab.research.google.com/github/Omkar210/Statistics-and-ML/blob/main/Day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [3]:
import os
print(os.getcwd())
os.chdir('/content/drive/MyDrive/CDAC')
os.getcwd()

/content

'/content/drive/MyDrive/CDAC'

In [4]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='ERPData')
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [5]:
x1 = np.random.randint(10, 80, 50)
df['Value'] = x1
df.head()

  MaterialID Location  Quantity  Value
0    TMI-43T    MWH-4        34     69
1    AXCP-78    MWH-1        67     55
2    LXCV-21    MWH-2        27     20
3    AXCP-78    MWH-5        65     20
4    AXCP-78    MWH-4        36     77

In [9]:
grp1 = df.groupby('MaterialID')
grp1.groups

{'AXCP-78': [1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48], 'DDBN-89': [22, 23, 26, 30, 40, 43, 45, 49], 'GCVB-79': [8, 15, 34, 35, 36], 'LXCV-21': [2, 27, 28, 29, 44], 'SDRT-67': [10, 11, 16, 17, 41, 42], 'TMI-43T': [0, 5, 6, 7, 9, 12, 13, 14, 18, 19, 20, 21, 31, 32, 33]}

In [12]:
grp1.get_group('DDBN-89')

   MaterialID Location  Quantity  Value
22    DDBN-89    MWH-4        48     65
23    DDBN-89    MWH-5        71     74
26    DDBN-89    MWH-1        57     24
30    DDBN-89    MWH-4        27     38
40    DDBN-89    MWH-1        34     50
43    DDBN-89    MWH-3        38     28
45    DDBN-89    MWH-2        69     63
49    DDBN-89    MWH-1        39     76

In [14]:
round(grp1.Quantity.mean(),2)

MaterialID
AXCP-78    81.64
DDBN-89    47.88
GCVB-79    36.40
LXCV-21    48.60
SDRT-67    49.00
TMI-43T    59.00
Name: Quantity, dtype: float64

In [15]:
grp1.Quantity.agg(['mean','sum','size'])

                 mean  sum  size
MaterialID
AXCP-78     81.636364  898    11
DDBN-89     47.875000  383     8
GCVB-79     36.400000  182     5
LXCV-21     48.600000  243     5
SDRT-67     49.000000  294     6
TMI-43T     59.000000  885    15

In [23]:
s1 = grp1.Quantity.agg('size')
d1 = pd.DataFrame(s1)
print(d1)
d1.loc['SDRT-67']

            Quantity
MaterialID
AXCP-78           11
DDBN-89            8
GCVB-79            5
LXCV-21            5
SDRT-67            6
TMI-43T           15

Quantity    6
Name: SDRT-67, dtype: int64

In [29]:
d1.iloc[np.where(d1.index=='SDRT-67')[0]]

            Quantity
MaterialID
SDRT-67            6

In [30]:
grp1.Quantity.agg(['mean','sum','size']).loc['SDRT-67','sum']

np.int64(294)