<a href="https://colab.research.google.com/github/Omkar210/Statistics-and-ML/blob/main/Day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
import os
print(os.getcwd())
os.chdir('/content/drive/MyDrive/CDAC')
os.getcwd()

/content

'/content/drive/MyDrive/CDAC'

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='ERPData')
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

## groupby command Revision

In [ ]:
x1 = np.random.randint(10, 80, 50)
df['Value'] = x1
df.head()

  MaterialID Location  Quantity  Value
0    TMI-43T    MWH-4        34     69
1    AXCP-78    MWH-1        67     55
2    LXCV-21    MWH-2        27     20
3    AXCP-78    MWH-5        65     20
4    AXCP-78    MWH-4        36     77

In [ ]:
grp1 = df.groupby('MaterialID')
grp1.groups

{'AXCP-78': [1, 3, 4, 24, 25, 37, 38, 39, 46, 47, 48], 'DDBN-89': [22, 23, 26, 30, 40, 43, 45, 49], 'GCVB-79': [8, 15, 34, 35, 36], 'LXCV-21': [2, 27, 28, 29, 44], 'SDRT-67': [10, 11, 16, 17, 41, 42], 'TMI-43T': [0, 5, 6, 7, 9, 12, 13, 14, 18, 19, 20, 21, 31, 32, 33]}

In [ ]:
grp1.get_group('DDBN-89')

   MaterialID Location  Quantity  Value
22    DDBN-89    MWH-4        48     65
23    DDBN-89    MWH-5        71     74
26    DDBN-89    MWH-1        57     24
30    DDBN-89    MWH-4        27     38
40    DDBN-89    MWH-1        34     50
43    DDBN-89    MWH-3        38     28
45    DDBN-89    MWH-2        69     63
49    DDBN-89    MWH-1        39     76

In [ ]:
round(grp1.Quantity.mean(),2)

MaterialID
AXCP-78    81.64
DDBN-89    47.88
GCVB-79    36.40
LXCV-21    48.60
SDRT-67    49.00
TMI-43T    59.00
Name: Quantity, dtype: float64

In [ ]:
grp1.Quantity.agg(['mean','sum','size'])

                 mean  sum  size
MaterialID
AXCP-78     81.636364  898    11
DDBN-89     47.875000  383     8
GCVB-79     36.400000  182     5
LXCV-21     48.600000  243     5
SDRT-67     49.000000  294     6
TMI-43T     59.000000  885    15

In [ ]:
s1 = grp1.Quantity.agg('size')
d1 = pd.DataFrame(s1)
print(d1)
d1.loc['SDRT-67']

            Quantity
MaterialID
AXCP-78           11
DDBN-89            8
GCVB-79            5
LXCV-21            5
SDRT-67            6
TMI-43T           15

Quantity    6
Name: SDRT-67, dtype: int64

In [ ]:
d1.iloc[np.where(d1.index=='SDRT-67')[0]]

            Quantity
MaterialID
SDRT-67            6

In [ ]:
grp1.Quantity.agg(['mean','sum','size']).loc['SDRT-67','sum']

np.int64(294)

In [ ]:
grp1.Quantity.agg(['mean','sum','size']).iloc[4,1]

np.int64(294)

# Shaping Dataset

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='Health')
df

   Country       Disease  2019  2020  2021
0    India        Cancer    12    94    35
1       UK        Cancer    95    19    84
2       US        Cancer    98    19    53
3    Japan        Cancer    89    52    14
4    India         Covid    38    19    62
5       UK         Covid    69    73    35
6       US         Covid    87    97    35
7    Japan         Covid    14    12    90
8    India  Heart Attack    84    10    98
9       UK  Heart Attack    44    17    24
10      US  Heart Attack    34    40    54
11   Japan  Heart Attack    11    43    75

Long Format

In [ ]:
df1 = df.melt(id_vars=['Country','Disease'],var_name='Year',value_name='Cases')
df1.head(10)

  Country       Disease  Year  Cases
0   India        Cancer  2019     12
1      UK        Cancer  2019     95
2      US        Cancer  2019     98
3   Japan        Cancer  2019     89
4   India         Covid  2019     38
5      UK         Covid  2019     69
6      US         Covid  2019     87
7   Japan         Covid  2019     14
8   India  Heart Attack  2019     84
9      UK  Heart Attack  2019     44

Wider format

In [ ]:
# Disease and Country will be in Multi-index
df2 = df1.pivot_table(values='Cases', index=['Country','Year'], columns='Disease')
print(df2)
df2.xs(2020,level=1)

Disease       Cancer  Covid  Heart Attack
Country Year
India   2019    12.0   38.0          84.0
        2020    94.0   19.0          10.0
        2021    35.0   62.0          98.0
Japan   2019    89.0   14.0          11.0
        2020    52.0   12.0          43.0
        2021    14.0   90.0          75.0
UK      2019    95.0   69.0          44.0
        2020    19.0   73.0          17.0
        2021    84.0   35.0          24.0
US      2019    98.0   87.0          34.0
        2020    19.0   97.0          40.0
        2021    53.0   35.0          54.0

Disease  Cancer  Covid  Heart Attack
Country
India      94.0   19.0          10.0
Japan      52.0   12.0          43.0
UK         19.0   73.0          17.0
US         19.0   97.0          40.0

In [ ]:
# Disease and Country will be in Column not in label
df2 = df1.pivot_table(values='Cases', index=['Country','Year'], columns='Disease').reset_index()
df2

Disease Country  Year  Cancer  Covid  Heart Attack
0         India  2019    12.0   38.0          84.0
1         India  2020    94.0   19.0          10.0
2         India  2021    35.0   62.0          98.0
3         Japan  2019    89.0   14.0          11.0
4         Japan  2020    52.0   12.0          43.0
5         Japan  2021    14.0   90.0          75.0
6            UK  2019    95.0   69.0          44.0
7            UK  2020    19.0   73.0          17.0
8            UK  2021    84.0   35.0          24.0
9            US  2019    98.0   87.0          34.0
10           US  2020    19.0   97.0          40.0
11           US  2021    53.0   35.0          54.0

In [ ]:
df2.index

MultiIndex([('India', 2019),
            ('India', 2020),
            ('India', 2021),
            ('Japan', 2019),
            ('Japan', 2020),
            ('Japan', 2021),
            (   'UK', 2019),
            (   'UK', 2020),
            (   'UK', 2021),
            (   'US', 2019),
            (   'US', 2020),
            (   'US', 2021)],
           names=['Country', 'Year'])

In [ ]:
# Disease label will get remove 'rename_axis(columns=None)'
df2 = df1.pivot_table(values='Cases', index=['Country','Year'], columns='Disease').reset_index().rename_axis(columns=None)
df2.head()

  Country  Year  Cancer  Covid  Heart Attack
0   India  2019    12.0   38.0          84.0
1   India  2020    94.0   19.0          10.0
2   India  2021    35.0   62.0          98.0
3   Japan  2019    89.0   14.0          11.0
4   Japan  2020    52.0   12.0          43.0

### ERP Data

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='ERPData')
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
# aggfunc is used by pivot_table is mean by default
df1 = df.pivot_table(values='Quantity',index=['MaterialID'],columns='Location',aggfunc='sum')
df1

Location    MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
MaterialID
AXCP-78     548.0   85.0   29.0   36.0  200.0
DDBN-89     130.0   69.0   38.0   75.0   71.0
GCVB-79       NaN  156.0    NaN    NaN   26.0
LXCV-21       NaN   27.0   42.0    NaN  174.0
SDRT-67      91.0   31.0    NaN   58.0  114.0
TMI-43T     120.0   29.0   65.0  559.0  112.0

In [ ]:
df2 = df.pivot_table(values='Quantity',index=['MaterialID'],columns='Location',aggfunc='size')
df2

Location    MWH-1  MWH-2  MWH-3  MWH-4  MWH-5
MaterialID
AXCP-78       5.0    1.0    1.0    1.0    3.0
DDBN-89       3.0    1.0    1.0    2.0    1.0
GCVB-79       NaN    4.0    NaN    NaN    1.0
LXCV-21       NaN    1.0    1.0    NaN    3.0
SDRT-67       2.0    1.0    NaN    1.0    2.0
TMI-43T       1.0    1.0    1.0   11.0    1.0

# **Type of Data**

### 1. Qualitative / Categorical / Attribute: Mostly Categorical Data(Strings)

### 2. Quantitative: Numbers(Age, Scores)


- Continuous Data: Is the one where possibility of decimal point cannot be ruled out.
ex: will always be the measure and the measurment will be coming from instrument -> Weight, Height

- Discrete Data: Data where possibility of decimal point is completely ruled out.
ex: will always be the result of count and will never have a decimal point

- when n*p and n*(1-p) then discreate data can be considered as continuous

- Any Rating or Ranking is number is categorical data

**Googly Question:** Money related Data will Discrete.

---

# **Types of Scale**

1. Nominal: What is your Gender? (Male or Female) <- Category
Category don't have logical order (Female or Male) there will be same Answer

2. Ordinal: Order Matters
Rating in 1 to 5, 1 is poor and 5 is excellent and if 1 is Excellent and 5 is poor then the answer will be change.

3. Interval: 0(zero) doesn't mean absence of measure, so mathematical calculation/operation will be restricted. Ex: Temperature: 0 C => 0 is like 0 deg temp but zero mean not like temp is not exist.
- Cannot take Ratio
- They are comparable

4. Ratio

Ratio = p/q both are countinuous ex: dist / time

proportion = p/q both are discrete ex: number of poeple from maharashtra / total number of people in class is discrete.

---
Discriptive Stat

1. Data Summarization
2. Data Visualization

Inferantial Stat
1. Hypotheysis Testing

Predictive Stat
1. Time-series Modeling
2. AI Model

# Data Summarization for Categorical Data

This things can be done:
- Count
- Proportion
- Percentage
- Cummilative Percentage/Proportion/Count
- Sorting

In [ ]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='ERPData')
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [ ]:
x1 = df.MaterialID

In [ ]:
np.unique(x1)

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [ ]:
len(np.unique(x1))

6

In [ ]:
np.unique(x1, return_counts=True)

(array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
       dtype=object),
 array([11,  8,  5,  5,  6, 15]))

In [ ]:
x1.value_counts()

MaterialID
TMI-43T    15
AXCP-78    11
DDBN-89     8
SDRT-67     6
GCVB-79     5
LXCV-21     5
Name: count, dtype: int64

In [ ]:
print(x1.value_counts().reset_index(drop=True))
df1 = x1.value_counts().reset_index()
df1

0    15
1    11
2     8
3     6
4     5
5     5
Name: count, dtype: int64

  MaterialID  count
0    TMI-43T     15
1    AXCP-78     11
2    DDBN-89      8
3    SDRT-67      6
4    GCVB-79      5
5    LXCV-21      5

In [ ]:
df1['prop'] = df1['count']/sum(df1['count'])
df1

  MaterialID  count  prop
0    TMI-43T     15  0.30
1    AXCP-78     11  0.22
2    DDBN-89      8  0.16
3    SDRT-67      6  0.12
4    GCVB-79      5  0.10
5    LXCV-21      5  0.10

In [ ]:
df1['pct'] = df1['prop']*100
df1

  MaterialID  count  prop   pct
0    TMI-43T     15  0.30  30.0
1    AXCP-78     11  0.22  22.0
2    DDBN-89      8  0.16  16.0
3    SDRT-67      6  0.12  12.0
4    GCVB-79      5  0.10  10.0
5    LXCV-21      5  0.10  10.0

In [ ]:
# Top three conssignment has total percentage count
df1['CumPct'] = np.cumsum(df1['pct'])
df1

  MaterialID  count  prop   pct  CumPct
0    TMI-43T     15  0.30  30.0    30.0
1    AXCP-78     11  0.22  22.0    52.0
2    DDBN-89      8  0.16  16.0    68.0
3    SDRT-67      6  0.12  12.0    80.0
4    GCVB-79      5  0.10  10.0    90.0
5    LXCV-21      5  0.10  10.0   100.0

## Descriptive Statistics
Central Tendency : Mean, Mode, Median

Dispersion or Variance or Speed : Range, Inter-Quartile Range, Variation and Standard Deviation

Shape : Skewness, Kurtosis

In [ ]:
# Mean of x*f
# Problem : Weighted Average/Mean
x = np.array([3,4,5,6])
f = np.array([20,18,9,12])

sum(x*f)/sum(f)

np.float64(4.220338983050848)

Mean:
- Mean Should be used when there are no extreme value in the data set
- Mean should be used when data is Symetrical
- Median can be used in all cases.

Mode: It can be used for Qualitative and it have multiple value as well.
* 1-Mode : Mode
* 2-Mode : Bi-Mode
* 3-Mode : Tri-Mode
* 3+ Mode : Multi-Mode